<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="waf" nsURI="http://www.cs.man.ac.uk/mdsd/2015/WebApplicationFramework"
    nsPrefix="waf">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EEnum" name="FrameworkTechnologies">
    <eLiterals name="JSF"/>
    <eLiterals name="CakePHP" value="1"/>
    <eLiterals name="CodeIgniter" value="2"/>
    <eLiterals name="Kohana" value="3"/>
    <eLiterals name="Laravel" value="4" literal="Laravel"/>
    <eLiterals name="Symfony" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AjaxTechnologies">
    <eLiterals name="None"/>
    <eLiterals name="jQuery" value="1"/>
    <eLiterals name="AngularJS" value="2" literal="AngularJS"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WafModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="persistence" lowerBound="1"
        eType="ecore:EClass ../../uk.ac.man.cs.mdsd.orm.model/model/orm.ecore#//OrmModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="services" upperBound="-1"
        eType="#//Service" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pages" upperBound="-1"
        eType="#//Page" containment="true" eOpposite="#//Page/partOf"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="menus" upperBound="-1"
        eType="#//Menu" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="siteName" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="siteTitle" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="developmentVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baseURL" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rewriteURLs" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="webmasterEmail" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="copyrightText" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaDescription" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="frameworkTechnology" ordered="false"
        lowerBound="1" eType="#//FrameworkTechnologies"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ajaxTechnology" eType="#//AjaxTechnologies"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="authentication" ordered="false"
        eType="#//Authentication" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="captchaSiteKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="captchaSecretKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="textEditorURL" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="topNavigationId" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sideMenu" ordered="false"
        eType="#//Menu"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="staticUnitsEditable" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Authentication" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="loginLabel" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="logoutLabel" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalAuthenticationSystem" eSuperTypes="#//Authentication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="userService" ordered="false"
        lowerBound="1" eType="#//Service"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="userAuthenticationKey"
        ordered="false" lowerBound="1" eType="#//ServiceEntityElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="authenticationService"
        ordered="false" eType="#//Service"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="loginAttemptService" ordered="false"
        eType="#//Service"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="autoLoginService" ordered="false"
        eType="#//Service"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="allowSelfRegistration"
        ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="useEmailActivation" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sendWelcomeEmail" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="registrationUnit" ordered="false"
        eType="#//RegistrationUnit" eOpposite="#//RegistrationUnit/authenticationSystem"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="loginUnit" ordered="false"
        lowerBound="1" eType="#//LoginUnit" eOpposite="#//LoginUnit/authenticationSystem"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="forgottenPasswordUnit"
        ordered="false" eType="#//ForgottenPasswordUnit" eOpposite="#//ForgottenPasswordUnit/authenticationSystem"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CasAuthentication" eSuperTypes="#//Authentication"/>
  <eClassifiers xsi:type="ecore:EClass" name="IncludedFeature" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayLabel" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="forcedValue" ordered="false"
        eType="ecore:EClass ../../uk.ac.man.cs.mdsd.criteria.model/model/Criteria.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="footer" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="headerClass" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inputClass" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayClass" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="footerClass" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IncludedElement" abstract="true" interface="true"
      eSuperTypes="#//IncludedFeature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="obfuscateFormFields" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultValue" ordered="false"
        eType="ecore:EClass ../../uk.ac.man.cs.mdsd.criteria.model/model/Criteria.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IncludedAssociation" abstract="true"
      interface="true" eSuperTypes="#//IncludedFeature"/>
  <eClassifiers xsi:type="ecore:EClass" name="Service" eSuperTypes="../../uk.ac.man.cs.mdsd.orm.model/model/orm.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entities" lowerBound="1"
        upperBound="-1" eType="ecore:EClass ../../uk.ac.man.cs.mdsd.orm.model/model/orm.ecore#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="daosUsed" lowerBound="1"
        upperBound="-1" eType="ecore:EClass ../../uk.ac.man.cs.mdsd.orm.model/model/orm.ecore#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelName" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="view" ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="viewName" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="displayLabels" upperBound="-1"
        eType="#//ModelLabel" containment="true" eOpposite="#//ModelLabel/labelFor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selections" upperBound="-1"
        eType="#//Selection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//ServiceFeature" containment="true" eOpposite="#//ServiceFeature/includedBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="accessedBy" upperBound="-1"
        eType="#//DynamicUnit" eOpposite="#//DynamicUnit/service"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelLabel" eSuperTypes="../../uk.ac.man.cs.mdsd.orm.model/model/orm.ecore#//NamedElement #//UnitTitle">
    <eStructuralFeatures xsi:type="ecore:EReference" name="labelFor" ordered="false"
        lowerBound="1" eType="#//Service" eOpposite="#//Service/displayLabels"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="format" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" lowerBound="1"
        upperBound="-1" eType="#//ServiceFeature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Selection" eSuperTypes="../../uk.ac.man.cs.mdsd.orm.model/model/orm.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="joins" upperBound="-1"
        eType="#//ServiceAssociation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filter" ordered="false"
        eType="ecore:EClass ../../uk.ac.man.cs.mdsd.criteria.model/model/Criteria.ecore#//Predicate"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ordering" upperBound="-1"
        eType="ecore:EClass ../../uk.ac.man.cs.mdsd.criteria.model/model/Criteria.ecore#//Order"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="limit" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceFeature" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="includedBy" ordered="false"
        lowerBound="1" eType="#//Service" eOpposite="#//Service/features"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cardinality" ordered="false"
        lowerBound="1" eType="ecore:EEnum ../../uk.ac.man.cs.mdsd.orm.model/model/orm.ecore#//Cardinality"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateFormat" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceEntityFeature" abstract="true"
      eSuperTypes="#//IncludedFeature #//ServiceFeature ../../uk.ac.man.cs.mdsd.orm.model/model/orm.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="viewColumnName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceEntityElement" eSuperTypes="#//ServiceEntityFeature #//IncludedElement #//UnitTitle">
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../uk.ac.man.cs.mdsd.orm.model/model/orm.ecore#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="caseInsensitive" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="encrypt" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="placeholder" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validationPattern" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceAssociation" abstract="true"
      interface="true" eSuperTypes="#//ServiceFeature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="oppositeService" lowerBound="1"
        eType="#//Service"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="oppositeFeature" ordered="false"
        eType="#//ServiceAssociation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceEntityAssociation" eSuperTypes="#//ServiceEntityFeature #//ServiceAssociation #//IncludedAssociation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../uk.ac.man.cs.mdsd.orm.model/model/orm.ecore#//Association"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceViewAssociation" eSuperTypes="../../uk.ac.man.cs.mdsd.orm.model/model/orm.ecore#//NamedDisplayElement #//ServiceAssociation"/>
  <eClassifiers xsi:type="ecore:EEnum" name="PageTopMenuOptions">
    <eLiterals name="NeverInclude"/>
    <eLiterals name="AlwaysInclude"/>
    <eLiterals name="IncludeWhenAuthenticated"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Page" eSuperTypes="../../uk.ac.man.cs.mdsd.orm.model/model/orm.ecore#//NamedDisplayElement #//UnitContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="partOf" eType="#//WafModel"
        eOpposite="#//WafModel/pages"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentPage" eType="#//Page"
        eOpposite="#//Page/childPages"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childPages" upperBound="-1"
        eType="#//Page" eOpposite="#//Page/parentPage"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="authenticated" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="topMenuOption" lowerBound="1"
        eType="#//PageTopMenuOptions"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="topMenuRank" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="navigationLabel" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sideMenu" ordered="false"
        eType="#//Menu"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="styleClass" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Menu" abstract="true" eSuperTypes="../../uk.ac.man.cs.mdsd.orm.model/model/orm.ecore#//NamedDisplayElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entries" upperBound="-1"
        eType="#//MenuEntry" containment="true" eOpposite="#//MenuEntry/partOf"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="omitCaption" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="captionClass" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="styleClass" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="layoutClass" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MenuEntry" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="partOf" ordered="false"
        lowerBound="1" eType="#//Menu" eOpposite="#//Menu/entries"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StaticMenu" eSuperTypes="#//Menu"/>
  <eClassifiers xsi:type="ecore:EClass" name="FixedPageMenuEntry" eSuperTypes="#//MenuEntry ../../uk.ac.man.cs.mdsd.orm.model/model/orm.ecore#//NamedDisplayElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="destination" ordered="false"
        lowerBound="1" eType="#//Page"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FixedActionMenuEntry" eSuperTypes="#//MenuEntry ../../uk.ac.man.cs.mdsd.orm.model/model/orm.ecore#//NamedDisplayElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="destination" ordered="false"
        lowerBound="1" eType="#//DynamicUnit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FixedCommandMenuEntry" eSuperTypes="#//MenuEntry ../../uk.ac.man.cs.mdsd.orm.model/model/orm.ecore#//NamedDisplayElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="destination" eType="#//Command"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EditStaticTextMenuEntry" eSuperTypes="#//MenuEntry ../../uk.ac.man.cs.mdsd.orm.model/model/orm.ecore#//NamedDisplayElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="DynamicMenu" eSuperTypes="#//Menu">
    <eStructuralFeatures xsi:type="ecore:EReference" name="service" ordered="false"
        lowerBound="1" eType="#//Service"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selection" ordered="false"
        lowerBound="1" eType="#//Selection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dynamicTitle" ordered="false"
        eType="#//ServiceEntityElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MenuIncludedFeature" abstract="true"
      eSuperTypes="#//MenuEntry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayLabel" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MenuIncludedElement" eSuperTypes="#//MenuIncludedFeature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
        <details key="derivation" value="if feature.oclIsUndefined() then '' else feature.name endif"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../uk.ac.man.cs.mdsd.orm.model/model/orm.ecore#//SingletonAttribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectTarget" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="targettingActions" upperBound="-1"
        eType="#//SelectAction" eOpposite="#//SelectAction/target"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnitContainer" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="units" upperBound="-1"
        eType="#//ContentUnit" containment="true" eOpposite="#//ContentUnit/displayedOn"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnitTitle" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ContentUnit" abstract="true" eSuperTypes="../../uk.ac.man.cs.mdsd.orm.model/model/orm.ecore#//NamedDisplayElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="displayedOn" ordered="false"
        lowerBound="1" eType="#//UnitContainer" eOpposite="#//UnitContainer/units"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="purposeSummary" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="omitCaption" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="captionClass" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="styleClass" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="layoutClass" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StaticUnit" eSuperTypes="#//ContentUnit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="service" ordered="false"
        eType="#//Service"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommandUnit" eSuperTypes="#//ContentUnit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="commands" upperBound="-1"
        eType="#//Command" containment="true" eOpposite="#//Command/partOf"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Command" abstract="true" eSuperTypes="../../uk.ac.man.cs.mdsd.orm.model/model/orm.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="partOf" lowerBound="1"
        eType="#//CommandUnit" eOpposite="#//CommandUnit/commands"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserCommand" eSuperTypes="#//Command"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreateSitemapUnit" eSuperTypes="#//ContentUnit">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deployedURL" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filename" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DynamicUnit" abstract="true" eSuperTypes="#//ContentUnit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="service" ordered="false"
        lowerBound="1" eType="#//Service" eOpposite="#//Service/accessedBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="displayFields" upperBound="-1"
        eType="#//UnitField" containment="true" eOpposite="#//UnitField/displayedOn"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supportActions" upperBound="-1"
        eType="#//UnitSupportAction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="header" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="footer" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="headerClass" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="controlClass" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="footerClass" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="errorClass" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnitField" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="displayedOn" ordered="false"
        lowerBound="1" eType="#//DynamicUnit" eOpposite="#//DynamicUnit/displayFields"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cardinality" ordered="false"
        lowerBound="1" eType="ecore:EEnum ../../uk.ac.man.cs.mdsd.orm.model/model/orm.ecore#//Cardinality"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateFormat" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CollectionDisplayOptions">
    <eLiterals name="LineDirection"/>
    <eLiterals name="PageDirection" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnitFeature" abstract="true" eSuperTypes="../../uk.ac.man.cs.mdsd.orm.model/model/orm.ecore#//NamedElement #//IncludedFeature #//UnitField #//InlineActionContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="onlyDisplayWhenNotEmpty"
        ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayOption" ordered="false"
        eType="#//CollectionDisplayOptions" defaultValueLiteral="LineDirection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkedAction" ordered="false"
        eType="#//SelectAction"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumDisplaySize" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="autofocus" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnitElement" eSuperTypes="#//UnitFeature #//IncludedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceFeature" ordered="false"
        lowerBound="1" eType="#//ServiceEntityElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="placeholder" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validationPattern" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnitAssociation" eSuperTypes="#//UnitFeature #//IncludedAssociation #//UnitContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceFeature" ordered="false"
        lowerBound="1" eType="#//ServiceAssociation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childFeature" eType="#//UnitChildFeature"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selection" ordered="false"
        eType="#//Selection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dynamicLabel" ordered="false"
        eType="#//ModelLabel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filters" upperBound="-1"
        eType="#//UnitTitle"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnitChildFeature" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="UnitChildElement" eSuperTypes="#//UnitChildFeature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceFeature" ordered="false"
        lowerBound="1" eType="#//ServiceEntityElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnitChildAssociation" eSuperTypes="#//UnitChildFeature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceFeature" ordered="false"
        lowerBound="1" eType="#//ServiceAssociation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childFeature" eType="#//UnitChildFeature"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InterfaceField" abstract="true" eSuperTypes="../../uk.ac.man.cs.mdsd.orm.model/model/orm.ecore#//NamedDisplayElement #//UnitField">
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultValue" ordered="false"
        eType="ecore:EClass ../../uk.ac.man.cs.mdsd.criteria.model/model/Criteria.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inputClass" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mustMatch" ordered="false"
        eType="#//UnitField"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataTypeField" eSuperTypes="#//InterfaceField">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataType" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../uk.ac.man.cs.mdsd.orm.model/model/orm.ecore#//DataType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="caseInsensitive" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="obfuscateFormFields" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="encrypt" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DateField" eSuperTypes="#//InterfaceField">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="details" lowerBound="1"
        eType="ecore:EEnum ../../uk.ac.man.cs.mdsd.orm.model/model/orm.ecore#//DateDetails"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="format" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CaptchaField" eSuperTypes="../../uk.ac.man.cs.mdsd.orm.model/model/orm.ecore#//NamedDisplayElement #//UnitField"/>
  <eClassifiers xsi:type="ecore:EClass" name="UnitSupportAction" eSuperTypes="../../uk.ac.man.cs.mdsd.orm.model/model/orm.ecore#//NamedDisplayElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="confirmMessage" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EditUnit" abstract="true" eSuperTypes="#//DynamicUnit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="confirmDestination" ordered="false"
        eType="#//Page"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="confirmLabel" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cancelDestination" ordered="false"
        eType="#//Page"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cancelLabel" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CreateUnit" eSuperTypes="#//EditUnit"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreateUpdateUnit" eSuperTypes="#//EditUnit #//SelectTarget">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="clearLabel" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MapUnit" eSuperTypes="#//EditUnit #//SelectTarget">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="readOnly" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultZoomLevel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" eType="#//ServiceEntityElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="placeName" eType="#//ServiceEntityElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UpdateUnit" eSuperTypes="#//EditUnit #//SelectTarget"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataUnit" abstract="true" eSuperTypes="#//DynamicUnit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="selection" ordered="false"
        eType="#//Selection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dynamicTitle" ordered="false"
        eType="#//UnitTitle"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DetailsUnit" eSuperTypes="#//DataUnit #//SelectTarget">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="omitFieldLabels" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndexUnit" abstract="true" eSuperTypes="#//DataUnit #//InlineActionContainer #//SelectTarget">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="omitColumnLabels" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultPaginationSize"
        ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nextPageLabel" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="previousPageLabel" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="useFirstLastPageLinks"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstPageLabel" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastPageLabel" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targettingSearches" eType="#//SearchUnit"
        eOpposite="#//SearchUnit/resultsDestination"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rowClasses" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndexGridUnit" eSuperTypes="#//IndexUnit"/>
  <eClassifiers xsi:type="ecore:EClass" name="IndexPageDirectionUnit" eSuperTypes="#//IndexUnit"/>
  <eClassifiers xsi:type="ecore:EClass" name="IndexLineDirectionUnit" eSuperTypes="#//IndexUnit"/>
  <eClassifiers xsi:type="ecore:EClass" name="ControlUnit" abstract="true" eSuperTypes="#//DynamicUnit">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="submitLabel" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cancelDestination" ordered="false"
        eType="#//Page"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cancelLabel" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SearchUnit" eSuperTypes="#//ControlUnit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultsDestination" ordered="false"
        lowerBound="1" eType="#//IndexUnit" eOpposite="#//IndexUnit/targettingSearches"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActionUnit" eSuperTypes="#//ControlUnit">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="omitFieldLabels" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuthenticationUnit" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="RegistrationUnit" eSuperTypes="#//EditUnit #//AuthenticationUnit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="authenticationSystem" ordered="false"
        eType="#//LocalAuthenticationSystem" eOpposite="#//LocalAuthenticationSystem/registrationUnit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LoginUnit" eSuperTypes="#//ControlUnit #//AuthenticationUnit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="authenticationSystem" ordered="false"
        eType="#//LocalAuthenticationSystem" eOpposite="#//LocalAuthenticationSystem/loginUnit"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="loginIdField" ordered="false"
        lowerBound="1" eType="#//UnitField"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="passwordField" ordered="false"
        lowerBound="1" eType="#//UnitField"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rememberMeField" ordered="false"
        eType="#//UnitField"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForgottenPasswordUnit" eSuperTypes="#//ControlUnit #//AuthenticationUnit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="authenticationSystem" ordered="false"
        eType="#//LocalAuthenticationSystem" eOpposite="#//LocalAuthenticationSystem/forgottenPasswordUnit"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="loginIdField" ordered="false"
        lowerBound="1" eType="#//UnitField"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InlineActionContainer" abstract="true"
      interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//InlineAction" containment="true" eOpposite="#//InlineAction/usedBy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InlineAction" abstract="true" eSuperTypes="../../uk.ac.man.cs.mdsd.orm.model/model/orm.ecore#//NamedDisplayElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="usedBy" ordered="false"
        lowerBound="1" eType="#//InlineActionContainer" eOpposite="#//InlineActionContainer/actions"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="header" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="footer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="headerClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="footerClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectAction" eSuperTypes="#//InlineAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" ordered="false"
        lowerBound="1" eType="#//SelectTarget" eOpposite="#//SelectTarget/targettingActions"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeleteAction" eSuperTypes="#//InlineAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="destination" eType="#//Page"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="confirmMessage" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureSupportAction" eSuperTypes="#//InlineAction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="confirmMessage" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelReference" eSuperTypes="../../uk.ac.man.cs.mdsd.criteria.model/model/Criteria.ecore#//Path">
    <eStructuralFeatures xsi:type="ecore:EReference" name="unit" ordered="false" lowerBound="1"
        eType="#//DynamicUnit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureReference" eSuperTypes="../../uk.ac.man.cs.mdsd.criteria.model/model/Criteria.ecore#//Path">
    <eStructuralFeatures xsi:type="ecore:EReference" name="field" ordered="false"
        lowerBound="1" eType="#//ServiceEntityFeature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CurrentUserReference" eSuperTypes="../../uk.ac.man.cs.mdsd.criteria.model/model/Criteria.ecore#//Path"/>
</ecore:EPackage>
