<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="orm" nsURI="http://www.cs.man.ac.uk/mdsd/2010/ObjectRelationalMapping"
    nsPrefix="orm">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="OrmModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataTypes" upperBound="-1"
        eType="#//DataType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entities" upperBound="-1"
        eType="#//Entity" containment="true" eOpposite="#//Entity/partOf"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="collectionTypes" upperBound="-1"
        eType="#//CollectionType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="databaseTechnology" ordered="false"
        eType="#//DatabaseTechnologies" defaultValueLiteral="MySql"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="databasePrefix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="databaseHost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="databaseName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="databaseUsername" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="databasePassword" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ormTechnology" eType="#//OrmTechnologies"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Cardinality">
    <eLiterals name="Optional"/>
    <eLiterals name="Required" value="1"/>
    <eLiterals name="Many" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DatabaseTechnologies">
    <eLiterals name="MySql"/>
    <eLiterals name="Oracle" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OrmTechnologies">
    <eLiterals name="JPA"/>
    <eLiterals name="DataMapper" value="1"/>
    <eLiterals name="Idiorm" value="2"/>
    <eLiterals name="Kohana" value="3"/>
    <eLiterals name="DoctrineORM" value="4"/>
    <eLiterals name="DoctrineODM" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedDisplayElement" abstract="true"
      eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayLabel" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Classifier" abstract="true" eSuperTypes="#//NamedDisplayElement"/>
  <eClassifiers xsi:type="ecore:EEnum" name="CollectionTypes">
    <eLiterals name="Bag" literal="Bag"/>
    <eLiterals name="List" literal="List"/>
    <eLiterals name="OrderedSet" literal="OrderedSet"/>
    <eLiterals name="Set" literal="Set"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionType" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="collectionType" eType="#//CollectionTypes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementType" lowerBound="1"
        eType="#//Classifier"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="persistenceType" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="javaInterfaceType" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="javaImplementationType"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataType" eSuperTypes="#//Classifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="EnumerationType" eSuperTypes="#//DataType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumerations" upperBound="-1"
        eType="#//EnumerationLiteral" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumerationLiteral" eSuperTypes="#//NamedDisplayElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Entity" eSuperTypes="#//Classifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="partOf" ordered="false"
        lowerBound="1" eType="#//OrmModel" eOpposite="#//OrmModel/entities"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tableName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="keys" upperBound="-1" eType="#//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="autoKeyName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contains" upperBound="-1"
        eType="#//Entity" eOpposite="#//Entity/container"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" eType="#//Entity"
        eOpposite="#//Entity/contains"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//Feature" containment="true" eOpposite="#//Feature/parentEntity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="displayFeatures" upperBound="-1"
        eType="#//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayFormat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature" abstract="true" eSuperTypes="#//NamedDisplayElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="columnName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentEntity" lowerBound="1"
        eType="#//Entity" eOpposite="#//Entity/features"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inputField" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="headerClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inputClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="footerClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" abstract="true" eSuperTypes="#//Feature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="persistentType" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ormType" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SingletonAttribute" abstract="true"
      eSuperTypes="#//Attribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="required" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unique" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultValue" ordered="false"
        eType="ecore:EClass ../../uk.ac.man.cs.mdsd.criteria.model/model/Criteria.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionAttribute" abstract="true"
      eSuperTypes="#//Attribute"/>
  <eClassifiers xsi:type="ecore:EClass" name="SingletonElement" eSuperTypes="#//SingletonAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataType" ordered="false"
        lowerBound="1" eType="#//DataType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="obfuscateFormFields" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="caseInsensitive" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="encrypt" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionElement" eSuperTypes="#//CollectionAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="collectionType" lowerBound="1"
        eType="#//CollectionType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DateDetails">
    <eLiterals name="DateOnly" value="1" literal="DateOnly"/>
    <eLiterals name="TimeOnly" value="2" literal="TimeOnly"/>
    <eLiterals name="DateAndTime" value="3" literal="DateAndTime"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DateAttribute" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="details" eType="#//DateDetails"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SingletonDate" eSuperTypes="#//SingletonAttribute #//DateAttribute"/>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionDate" eSuperTypes="#//CollectionAttribute #//DateAttribute"/>
  <eClassifiers xsi:type="ecore:EClass" name="SingletonResource" abstract="true" eSuperTypes="#//SingletonAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumUploadSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validUploadMimeTypes" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validUploadExtensions"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uploadsWithinWebsite" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relativeUploadDirectory"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SingletonFile" eSuperTypes="#//SingletonResource"/>
  <eClassifiers xsi:type="ecore:EClass" name="SingletonImage" eSuperTypes="#//SingletonResource"/>
  <eClassifiers xsi:type="ecore:EClass" name="SingletonLocation" eSuperTypes="#//SingletonAttribute"/>
  <eClassifiers xsi:type="ecore:EClass" name="Association" abstract="true" eSuperTypes="#//Feature">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="onlyOneSourceEnd"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="onlyOneSourceEnd" value="sourceEnd xor opposite.sourceEnd"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="opposite" lowerBound="1"
        eType="#//Association" eOpposite="#//Association/opposite"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceEnd" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bidirectional" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="containment" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pivotTableName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SingletonAssociationRelationships">
    <eLiterals name="OneToOne" literal="OneToOne"/>
    <eLiterals name="ManyToOne" value="1" literal="ManyToOne"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SingletonAssociation" eSuperTypes="#//Association">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="required" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="associationRelationship"
        eType="#//SingletonAssociationRelationships"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CollectionAssociationRelationships">
    <eLiterals name="OneToMany" literal="OneToMany"/>
    <eLiterals name="ManyToMany" value="1" literal="ManyToMany"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionAssociation" eSuperTypes="#//Association">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="x"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="x" value="collectionType.elementType = opposite.parentEntity"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="collectionType" lowerBound="1"
        eType="#//CollectionType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="associationRelationship"
        eType="#//CollectionAssociationRelationships"/>
  </eClassifiers>
</ecore:EPackage>
