/**
 */
package work.andycarpenter.psms.waf.provider;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;
import org.eclipse.emf.common.util.ResourceLocator;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.edit.command.CommandParameter;
import org.eclipse.emf.edit.domain.EditingDomain;
import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IChildCreationExtender;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;
import work.andycarpenter.psms.base.BasePackage;
import work.andycarpenter.psms.base.Constant;
import work.andycarpenter.psms.base.util.BaseSwitch;
import work.andycarpenter.psms.expression.ExpressionPackage;
import work.andycarpenter.psms.expression.FunctionCall;
import work.andycarpenter.psms.expression.PredicateBooleanVariable;
import work.andycarpenter.psms.expression.PredicateComparisonOperator;
import work.andycarpenter.psms.expression.PredicateEqualityOperator;
import work.andycarpenter.psms.expression.PredicateInOperator;
import work.andycarpenter.psms.expression.PredicateIsEmpty;
import work.andycarpenter.psms.expression.PredicateIsNull;
import work.andycarpenter.psms.expression.PredicateIsOperator;
import work.andycarpenter.psms.expression.PredicateLikeOperator;
import work.andycarpenter.psms.expression.util.ExpressionSwitch;
import work.andycarpenter.psms.orm.AssociationReference;
import work.andycarpenter.psms.orm.Attribute;
import work.andycarpenter.psms.orm.Order;
import work.andycarpenter.psms.orm.OrmPackage;
import work.andycarpenter.psms.orm.util.OrmSwitch;
import work.andycarpenter.psms.waf.WafFactory;
import work.andycarpenter.psms.waf.util.WafAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class WafItemProviderAdapterFactory extends WafAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public WafItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.WafModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WafModelItemProvider wafModelItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.WafModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWafModelAdapter() {
		if (wafModelItemProvider == null) {
			wafModelItemProvider = new WafModelItemProvider(this);
		}

		return wafModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.LocalAuthenticationSystem} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LocalAuthenticationSystemItemProvider localAuthenticationSystemItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.LocalAuthenticationSystem}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLocalAuthenticationSystemAdapter() {
		if (localAuthenticationSystemItemProvider == null) {
			localAuthenticationSystemItemProvider = new LocalAuthenticationSystemItemProvider(this);
		}

		return localAuthenticationSystemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.CasAuthentication} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CasAuthenticationItemProvider casAuthenticationItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.CasAuthentication}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCasAuthenticationAdapter() {
		if (casAuthenticationItemProvider == null) {
			casAuthenticationItemProvider = new CasAuthenticationItemProvider(this);
		}

		return casAuthenticationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.ImageManipulation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ImageManipulationItemProvider imageManipulationItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.ImageManipulation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createImageManipulationAdapter() {
		if (imageManipulationItemProvider == null) {
			imageManipulationItemProvider = new ImageManipulationItemProvider(this);
		}

		return imageManipulationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.BackgroundFilter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BackgroundFilterItemProvider backgroundFilterItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.BackgroundFilter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBackgroundFilterAdapter() {
		if (backgroundFilterItemProvider == null) {
			backgroundFilterItemProvider = new BackgroundFilterItemProvider(this);
		}

		return backgroundFilterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.ThumbnailFilter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ThumbnailFilterItemProvider thumbnailFilterItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.ThumbnailFilter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createThumbnailFilterAdapter() {
		if (thumbnailFilterItemProvider == null) {
			thumbnailFilterItemProvider = new ThumbnailFilterItemProvider(this);
		}

		return thumbnailFilterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.Menu} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MenuItemProvider menuItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.Menu}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMenuAdapter() {
		if (menuItemProvider == null) {
			menuItemProvider = new MenuItemProvider(this);
		}

		return menuItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.SubmenuEntry} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SubmenuEntryItemProvider submenuEntryItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.SubmenuEntry}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSubmenuEntryAdapter() {
		if (submenuEntryItemProvider == null) {
			submenuEntryItemProvider = new SubmenuEntryItemProvider(this);
		}

		return submenuEntryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.ActionMenuEntry} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ActionMenuEntryItemProvider actionMenuEntryItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.ActionMenuEntry}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createActionMenuEntryAdapter() {
		if (actionMenuEntryItemProvider == null) {
			actionMenuEntryItemProvider = new ActionMenuEntryItemProvider(this);
		}

		return actionMenuEntryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.EditStaticTextMenuEntry} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EditStaticTextMenuEntryItemProvider editStaticTextMenuEntryItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.EditStaticTextMenuEntry}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEditStaticTextMenuEntryAdapter() {
		if (editStaticTextMenuEntryItemProvider == null) {
			editStaticTextMenuEntryItemProvider = new EditStaticTextMenuEntryItemProvider(this);
		}

		return editStaticTextMenuEntryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.Page} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PageItemProvider pageItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.Page}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPageAdapter() {
		if (pageItemProvider == null) {
			pageItemProvider = new PageItemProvider(this);
		}

		return pageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.Query} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected QueryItemProvider queryItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.Query}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createQueryAdapter() {
		if (queryItemProvider == null) {
			queryItemProvider = new QueryItemProvider(this);
		}

		return queryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.QueryParameter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected QueryParameterItemProvider queryParameterItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.QueryParameter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createQueryParameterAdapter() {
		if (queryParameterItemProvider == null) {
			queryParameterItemProvider = new QueryParameterItemProvider(this);
		}

		return queryParameterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.RouteActual} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RouteActualItemProvider routeActualItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.RouteActual}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRouteActualAdapter() {
		if (routeActualItemProvider == null) {
			routeActualItemProvider = new RouteActualItemProvider(this);
		}

		return routeActualItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.StaticUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StaticUnitItemProvider staticUnitItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.StaticUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStaticUnitAdapter() {
		if (staticUnitItemProvider == null) {
			staticUnitItemProvider = new StaticUnitItemProvider(this);
		}

		return staticUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.UnitAttribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UnitAttributeItemProvider unitAttributeItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.UnitAttribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUnitAttributeAdapter() {
		if (unitAttributeItemProvider == null) {
			unitAttributeItemProvider = new UnitAttributeItemProvider(this);
		}

		return unitAttributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.UnitAssociation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UnitAssociationItemProvider unitAssociationItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.UnitAssociation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUnitAssociationAdapter() {
		if (unitAssociationItemProvider == null) {
			unitAssociationItemProvider = new UnitAssociationItemProvider(this);
		}

		return unitAssociationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.FeaturePathAttribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FeaturePathAttributeItemProvider featurePathAttributeItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.FeaturePathAttribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFeaturePathAttributeAdapter() {
		if (featurePathAttributeItemProvider == null) {
			featurePathAttributeItemProvider = new FeaturePathAttributeItemProvider(this);
		}

		return featurePathAttributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.FeaturePathAssociation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FeaturePathAssociationItemProvider featurePathAssociationItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.FeaturePathAssociation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFeaturePathAssociationAdapter() {
		if (featurePathAssociationItemProvider == null) {
			featurePathAssociationItemProvider = new FeaturePathAssociationItemProvider(this);
		}

		return featurePathAssociationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.FeaturePathLabel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FeaturePathLabelItemProvider featurePathLabelItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.FeaturePathLabel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFeaturePathLabelAdapter() {
		if (featurePathLabelItemProvider == null) {
			featurePathLabelItemProvider = new FeaturePathLabelItemProvider(this);
		}

		return featurePathLabelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.ChildPathAttribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ChildPathAttributeItemProvider childPathAttributeItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.ChildPathAttribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createChildPathAttributeAdapter() {
		if (childPathAttributeItemProvider == null) {
			childPathAttributeItemProvider = new ChildPathAttributeItemProvider(this);
		}

		return childPathAttributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.ChildPathAssociation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ChildPathAssociationItemProvider childPathAssociationItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.ChildPathAssociation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createChildPathAssociationAdapter() {
		if (childPathAssociationItemProvider == null) {
			childPathAssociationItemProvider = new ChildPathAssociationItemProvider(this);
		}

		return childPathAssociationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.UnitLabel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UnitLabelItemProvider unitLabelItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.UnitLabel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUnitLabelAdapter() {
		if (unitLabelItemProvider == null) {
			unitLabelItemProvider = new UnitLabelItemProvider(this);
		}

		return unitLabelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.DataTypeField} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataTypeFieldItemProvider dataTypeFieldItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.DataTypeField}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataTypeFieldAdapter() {
		if (dataTypeFieldItemProvider == null) {
			dataTypeFieldItemProvider = new DataTypeFieldItemProvider(this);
		}

		return dataTypeFieldItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.DateField} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DateFieldItemProvider dateFieldItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.DateField}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDateFieldAdapter() {
		if (dateFieldItemProvider == null) {
			dateFieldItemProvider = new DateFieldItemProvider(this);
		}

		return dateFieldItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.CaptchaField} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CaptchaFieldItemProvider captchaFieldItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.CaptchaField}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCaptchaFieldAdapter() {
		if (captchaFieldItemProvider == null) {
			captchaFieldItemProvider = new CaptchaFieldItemProvider(this);
		}

		return captchaFieldItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.SingletonUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SingletonUnitItemProvider singletonUnitItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.SingletonUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSingletonUnitAdapter() {
		if (singletonUnitItemProvider == null) {
			singletonUnitItemProvider = new SingletonUnitItemProvider(this);
		}

		return singletonUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.CollectionUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CollectionUnitItemProvider collectionUnitItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.CollectionUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCollectionUnitAdapter() {
		if (collectionUnitItemProvider == null) {
			collectionUnitItemProvider = new CollectionUnitItemProvider(this);
		}

		return collectionUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.CreateUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CreateUnitItemProvider createUnitItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.CreateUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCreateUnitAdapter() {
		if (createUnitItemProvider == null) {
			createUnitItemProvider = new CreateUnitItemProvider(this);
		}

		return createUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.CreateUpdateUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CreateUpdateUnitItemProvider createUpdateUnitItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.CreateUpdateUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCreateUpdateUnitAdapter() {
		if (createUpdateUnitItemProvider == null) {
			createUpdateUnitItemProvider = new CreateUpdateUnitItemProvider(this);
		}

		return createUpdateUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.MapUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MapUnitItemProvider mapUnitItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.MapUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMapUnitAdapter() {
		if (mapUnitItemProvider == null) {
			mapUnitItemProvider = new MapUnitItemProvider(this);
		}

		return mapUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.UpdateUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UpdateUnitItemProvider updateUnitItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.UpdateUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUpdateUnitAdapter() {
		if (updateUnitItemProvider == null) {
			updateUnitItemProvider = new UpdateUnitItemProvider(this);
		}

		return updateUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.DetailsUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DetailsUnitItemProvider detailsUnitItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.DetailsUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDetailsUnitAdapter() {
		if (detailsUnitItemProvider == null) {
			detailsUnitItemProvider = new DetailsUnitItemProvider(this);
		}

		return detailsUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.IndexGridUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IndexGridUnitItemProvider indexGridUnitItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.IndexGridUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIndexGridUnitAdapter() {
		if (indexGridUnitItemProvider == null) {
			indexGridUnitItemProvider = new IndexGridUnitItemProvider(this);
		}

		return indexGridUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.IndexPageDirectionUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IndexPageDirectionUnitItemProvider indexPageDirectionUnitItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.IndexPageDirectionUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIndexPageDirectionUnitAdapter() {
		if (indexPageDirectionUnitItemProvider == null) {
			indexPageDirectionUnitItemProvider = new IndexPageDirectionUnitItemProvider(this);
		}

		return indexPageDirectionUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.IndexLineDirectionUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IndexLineDirectionUnitItemProvider indexLineDirectionUnitItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.IndexLineDirectionUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIndexLineDirectionUnitAdapter() {
		if (indexLineDirectionUnitItemProvider == null) {
			indexLineDirectionUnitItemProvider = new IndexLineDirectionUnitItemProvider(this);
		}

		return indexLineDirectionUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.Badge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BadgeItemProvider badgeItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.Badge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBadgeAdapter() {
		if (badgeItemProvider == null) {
			badgeItemProvider = new BadgeItemProvider(this);
		}

		return badgeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.TextCardsUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TextCardsUnitItemProvider textCardsUnitItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.TextCardsUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTextCardsUnitAdapter() {
		if (textCardsUnitItemProvider == null) {
			textCardsUnitItemProvider = new TextCardsUnitItemProvider(this);
		}

		return textCardsUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.DateCardsUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DateCardsUnitItemProvider dateCardsUnitItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.DateCardsUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDateCardsUnitAdapter() {
		if (dateCardsUnitItemProvider == null) {
			dateCardsUnitItemProvider = new DateCardsUnitItemProvider(this);
		}

		return dateCardsUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.ImageCardsUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ImageCardsUnitItemProvider imageCardsUnitItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.ImageCardsUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createImageCardsUnitAdapter() {
		if (imageCardsUnitItemProvider == null) {
			imageCardsUnitItemProvider = new ImageCardsUnitItemProvider(this);
		}

		return imageCardsUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.SliderUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SliderUnitItemProvider sliderUnitItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.SliderUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSliderUnitAdapter() {
		if (sliderUnitItemProvider == null) {
			sliderUnitItemProvider = new SliderUnitItemProvider(this);
		}

		return sliderUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.GalleryUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GalleryUnitItemProvider galleryUnitItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.GalleryUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGalleryUnitAdapter() {
		if (galleryUnitItemProvider == null) {
			galleryUnitItemProvider = new GalleryUnitItemProvider(this);
		}

		return galleryUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.SearchUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SearchUnitItemProvider searchUnitItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.SearchUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSearchUnitAdapter() {
		if (searchUnitItemProvider == null) {
			searchUnitItemProvider = new SearchUnitItemProvider(this);
		}

		return searchUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.RegistrationUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RegistrationUnitItemProvider registrationUnitItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.RegistrationUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRegistrationUnitAdapter() {
		if (registrationUnitItemProvider == null) {
			registrationUnitItemProvider = new RegistrationUnitItemProvider(this);
		}

		return registrationUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.LoginUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LoginUnitItemProvider loginUnitItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.LoginUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLoginUnitAdapter() {
		if (loginUnitItemProvider == null) {
			loginUnitItemProvider = new LoginUnitItemProvider(this);
		}

		return loginUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.LogoutUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LogoutUnitItemProvider logoutUnitItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.LogoutUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLogoutUnitAdapter() {
		if (logoutUnitItemProvider == null) {
			logoutUnitItemProvider = new LogoutUnitItemProvider(this);
		}

		return logoutUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.ForgottenPasswordUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ForgottenPasswordUnitItemProvider forgottenPasswordUnitItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.ForgottenPasswordUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createForgottenPasswordUnitAdapter() {
		if (forgottenPasswordUnitItemProvider == null) {
			forgottenPasswordUnitItemProvider = new ForgottenPasswordUnitItemProvider(this);
		}

		return forgottenPasswordUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.SecurityAction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SecurityActionItemProvider securityActionItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.SecurityAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSecurityActionAdapter() {
		if (securityActionItemProvider == null) {
			securityActionItemProvider = new SecurityActionItemProvider(this);
		}

		return securityActionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.SelectAction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SelectActionItemProvider selectActionItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.SelectAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSelectActionAdapter() {
		if (selectActionItemProvider == null) {
			selectActionItemProvider = new SelectActionItemProvider(this);
		}

		return selectActionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.DeleteAction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DeleteActionItemProvider deleteActionItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.DeleteAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDeleteActionAdapter() {
		if (deleteActionItemProvider == null) {
			deleteActionItemProvider = new DeleteActionItemProvider(this);
		}

		return deleteActionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.InstanceOperationAction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InstanceOperationActionItemProvider instanceOperationActionItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.InstanceOperationAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInstanceOperationActionAdapter() {
		if (instanceOperationActionItemProvider == null) {
			instanceOperationActionItemProvider = new InstanceOperationActionItemProvider(this);
		}

		return instanceOperationActionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.ContainerOperationAction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ContainerOperationActionItemProvider containerOperationActionItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.ContainerOperationAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createContainerOperationActionAdapter() {
		if (containerOperationActionItemProvider == null) {
			containerOperationActionItemProvider = new ContainerOperationActionItemProvider(this);
		}

		return containerOperationActionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.psms.waf.GeneralOperationAction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GeneralOperationActionItemProvider generalOperationActionItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.psms.waf.GeneralOperationAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGeneralOperationActionAdapter() {
		if (generalOperationActionItemProvider == null) {
			generalOperationActionItemProvider = new GeneralOperationActionItemProvider(this);
		}

		return generalOperationActionItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (wafModelItemProvider != null) wafModelItemProvider.dispose();
		if (localAuthenticationSystemItemProvider != null) localAuthenticationSystemItemProvider.dispose();
		if (casAuthenticationItemProvider != null) casAuthenticationItemProvider.dispose();
		if (imageManipulationItemProvider != null) imageManipulationItemProvider.dispose();
		if (backgroundFilterItemProvider != null) backgroundFilterItemProvider.dispose();
		if (thumbnailFilterItemProvider != null) thumbnailFilterItemProvider.dispose();
		if (menuItemProvider != null) menuItemProvider.dispose();
		if (submenuEntryItemProvider != null) submenuEntryItemProvider.dispose();
		if (actionMenuEntryItemProvider != null) actionMenuEntryItemProvider.dispose();
		if (editStaticTextMenuEntryItemProvider != null) editStaticTextMenuEntryItemProvider.dispose();
		if (pageItemProvider != null) pageItemProvider.dispose();
		if (queryItemProvider != null) queryItemProvider.dispose();
		if (queryParameterItemProvider != null) queryParameterItemProvider.dispose();
		if (staticUnitItemProvider != null) staticUnitItemProvider.dispose();
		if (routeActualItemProvider != null) routeActualItemProvider.dispose();
		if (unitAttributeItemProvider != null) unitAttributeItemProvider.dispose();
		if (unitAssociationItemProvider != null) unitAssociationItemProvider.dispose();
		if (featurePathAttributeItemProvider != null) featurePathAttributeItemProvider.dispose();
		if (featurePathAssociationItemProvider != null) featurePathAssociationItemProvider.dispose();
		if (featurePathLabelItemProvider != null) featurePathLabelItemProvider.dispose();
		if (childPathAttributeItemProvider != null) childPathAttributeItemProvider.dispose();
		if (childPathAssociationItemProvider != null) childPathAssociationItemProvider.dispose();
		if (unitLabelItemProvider != null) unitLabelItemProvider.dispose();
		if (dataTypeFieldItemProvider != null) dataTypeFieldItemProvider.dispose();
		if (dateFieldItemProvider != null) dateFieldItemProvider.dispose();
		if (captchaFieldItemProvider != null) captchaFieldItemProvider.dispose();
		if (singletonUnitItemProvider != null) singletonUnitItemProvider.dispose();
		if (collectionUnitItemProvider != null) collectionUnitItemProvider.dispose();
		if (createUnitItemProvider != null) createUnitItemProvider.dispose();
		if (createUpdateUnitItemProvider != null) createUpdateUnitItemProvider.dispose();
		if (mapUnitItemProvider != null) mapUnitItemProvider.dispose();
		if (updateUnitItemProvider != null) updateUnitItemProvider.dispose();
		if (detailsUnitItemProvider != null) detailsUnitItemProvider.dispose();
		if (indexGridUnitItemProvider != null) indexGridUnitItemProvider.dispose();
		if (indexPageDirectionUnitItemProvider != null) indexPageDirectionUnitItemProvider.dispose();
		if (indexLineDirectionUnitItemProvider != null) indexLineDirectionUnitItemProvider.dispose();
		if (badgeItemProvider != null) badgeItemProvider.dispose();
		if (textCardsUnitItemProvider != null) textCardsUnitItemProvider.dispose();
		if (dateCardsUnitItemProvider != null) dateCardsUnitItemProvider.dispose();
		if (imageCardsUnitItemProvider != null) imageCardsUnitItemProvider.dispose();
		if (sliderUnitItemProvider != null) sliderUnitItemProvider.dispose();
		if (galleryUnitItemProvider != null) galleryUnitItemProvider.dispose();
		if (searchUnitItemProvider != null) searchUnitItemProvider.dispose();
		if (registrationUnitItemProvider != null) registrationUnitItemProvider.dispose();
		if (loginUnitItemProvider != null) loginUnitItemProvider.dispose();
		if (logoutUnitItemProvider != null) logoutUnitItemProvider.dispose();
		if (forgottenPasswordUnitItemProvider != null) forgottenPasswordUnitItemProvider.dispose();
		if (securityActionItemProvider != null) securityActionItemProvider.dispose();
		if (selectActionItemProvider != null) selectActionItemProvider.dispose();
		if (deleteActionItemProvider != null) deleteActionItemProvider.dispose();
		if (instanceOperationActionItemProvider != null) instanceOperationActionItemProvider.dispose();
		if (containerOperationActionItemProvider != null) containerOperationActionItemProvider.dispose();
		if (generalOperationActionItemProvider != null) generalOperationActionItemProvider.dispose();
	}

	/**
	 * A child creation extender for the {@link OrmPackage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static class OrmChildCreationExtender implements IChildCreationExtender {
		/**
		 * The switch for creating child descriptors specific to each extended class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		protected static class CreationSwitch extends OrmSwitch<Object> {
			/**
			 * The child descriptors being populated.
			 * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
			 * @generated
			 */
			protected List<Object> newChildDescriptors;

			/**
			 * The domain in which to create the children.
			 * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
			 * @generated
			 */
			protected EditingDomain editingDomain;

			/**
			 * Creates the a switch for populating child descriptors in the given domain.
			 * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
			 * @generated
			 */
			CreationSwitch(List<Object> newChildDescriptors, EditingDomain editingDomain) {
				this.newChildDescriptors = newChildDescriptors;
				this.editingDomain = editingDomain;
			}
			/**
			 * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
			 * @generated
			 */
			@Override
			public Object caseAttribute(Attribute object) {
				newChildDescriptors.add
					(createChildParameter
						(OrmPackage.Literals.ATTRIBUTE__ATTRIBUTE_DEFAULT_VALUE,
						 WafFactory.eINSTANCE.createFeaturePathAttribute()));

				newChildDescriptors.add
					(createChildParameter
						(OrmPackage.Literals.ATTRIBUTE__ATTRIBUTE_DEFAULT_VALUE,
						 WafFactory.eINSTANCE.createFeaturePathAssociation()));

				newChildDescriptors.add
					(createChildParameter
						(OrmPackage.Literals.ATTRIBUTE__ATTRIBUTE_DEFAULT_VALUE,
						 WafFactory.eINSTANCE.createFeaturePathLabel()));

				return null;
			}
 
			/**
			 * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
			 * @generated
			 */
			@Override
			public Object caseAssociationReference(AssociationReference object) {
				newChildDescriptors.add
					(createChildParameter
						(OrmPackage.Literals.ASSOCIATION_REFERENCE__CHILD_FEATURE,
						 WafFactory.eINSTANCE.createChildPathAttribute()));

				newChildDescriptors.add
					(createChildParameter
						(OrmPackage.Literals.ASSOCIATION_REFERENCE__CHILD_FEATURE,
						 WafFactory.eINSTANCE.createChildPathAssociation()));

				return null;
			}
 
			/**
			 * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
			 * @generated
			 */
			@Override
			public Object caseOrder(Order object) {
				newChildDescriptors.add
					(createChildParameter
						(OrmPackage.Literals.ORDER__PATH,
						 WafFactory.eINSTANCE.createFeaturePathAttribute()));

				newChildDescriptors.add
					(createChildParameter
						(OrmPackage.Literals.ORDER__PATH,
						 WafFactory.eINSTANCE.createFeaturePathAssociation()));

				newChildDescriptors.add
					(createChildParameter
						(OrmPackage.Literals.ORDER__PATH,
						 WafFactory.eINSTANCE.createFeaturePathLabel()));

				return null;
			}
 
			/**
			 * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
			 * @generated
			 */
			protected CommandParameter createChildParameter(Object feature, Object child) {
				return new CommandParameter(null, feature, child);
			}

		}

		/**
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		public Collection<Object> getNewChildDescriptors(Object object, EditingDomain editingDomain) {
			ArrayList<Object> result = new ArrayList<Object>();
			new CreationSwitch(result, editingDomain).doSwitch((EObject)object);
			return result;
		}

		/**
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		public ResourceLocator getResourceLocator() {
			return WafEditPlugin.INSTANCE;
		}
	}

	/**
	 * A child creation extender for the {@link BasePackage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static class BaseChildCreationExtender implements IChildCreationExtender {
		/**
		 * The switch for creating child descriptors specific to each extended class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		protected static class CreationSwitch extends BaseSwitch<Object> {
			/**
			 * The child descriptors being populated.
			 * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
			 * @generated
			 */
			protected List<Object> newChildDescriptors;

			/**
			 * The domain in which to create the children.
			 * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
			 * @generated
			 */
			protected EditingDomain editingDomain;

			/**
			 * Creates the a switch for populating child descriptors in the given domain.
			 * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
			 * @generated
			 */
			CreationSwitch(List<Object> newChildDescriptors, EditingDomain editingDomain) {
				this.newChildDescriptors = newChildDescriptors;
				this.editingDomain = editingDomain;
			}
			/**
			 * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
			 * @generated
			 */
			@Override
			public Object caseConstant(Constant object) {
				newChildDescriptors.add
					(createChildParameter
						(BasePackage.Literals.CONSTANT__VALUE,
						 WafFactory.eINSTANCE.createFeaturePathAttribute()));

				newChildDescriptors.add
					(createChildParameter
						(BasePackage.Literals.CONSTANT__VALUE,
						 WafFactory.eINSTANCE.createFeaturePathAssociation()));

				newChildDescriptors.add
					(createChildParameter
						(BasePackage.Literals.CONSTANT__VALUE,
						 WafFactory.eINSTANCE.createFeaturePathLabel()));

				return null;
			}
 
			/**
			 * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
			 * @generated
			 */
			protected CommandParameter createChildParameter(Object feature, Object child) {
				return new CommandParameter(null, feature, child);
			}

		}

		/**
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		public Collection<Object> getNewChildDescriptors(Object object, EditingDomain editingDomain) {
			ArrayList<Object> result = new ArrayList<Object>();
			new CreationSwitch(result, editingDomain).doSwitch((EObject)object);
			return result;
		}

		/**
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		public ResourceLocator getResourceLocator() {
			return WafEditPlugin.INSTANCE;
		}
	}

	/**
	 * A child creation extender for the {@link ExpressionPackage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static class ExpressionChildCreationExtender implements IChildCreationExtender {
		/**
		 * The switch for creating child descriptors specific to each extended class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		protected static class CreationSwitch extends ExpressionSwitch<Object> {
			/**
			 * The child descriptors being populated.
			 * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
			 * @generated
			 */
			protected List<Object> newChildDescriptors;

			/**
			 * The domain in which to create the children.
			 * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
			 * @generated
			 */
			protected EditingDomain editingDomain;

			/**
			 * Creates the a switch for populating child descriptors in the given domain.
			 * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
			 * @generated
			 */
			CreationSwitch(List<Object> newChildDescriptors, EditingDomain editingDomain) {
				this.newChildDescriptors = newChildDescriptors;
				this.editingDomain = editingDomain;
			}
			/**
			 * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
			 * @generated
			 */
			@Override
			public Object caseFunctionCall(FunctionCall object) {
				newChildDescriptors.add
					(createChildParameter
						(ExpressionPackage.Literals.FUNCTION_CALL__ACTUALS,
						 WafFactory.eINSTANCE.createFeaturePathAttribute()));

				newChildDescriptors.add
					(createChildParameter
						(ExpressionPackage.Literals.FUNCTION_CALL__ACTUALS,
						 WafFactory.eINSTANCE.createFeaturePathAssociation()));

				newChildDescriptors.add
					(createChildParameter
						(ExpressionPackage.Literals.FUNCTION_CALL__ACTUALS,
						 WafFactory.eINSTANCE.createFeaturePathLabel()));

				return null;
			}
 
			/**
			 * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
			 * @generated
			 */
			@Override
			public Object casePredicateBooleanVariable(PredicateBooleanVariable object) {
				newChildDescriptors.add
					(createChildParameter
						(ExpressionPackage.Literals.PREDICATE_BOOLEAN_VARIABLE__FEATURE,
						 WafFactory.eINSTANCE.createFeaturePathAttribute()));

				newChildDescriptors.add
					(createChildParameter
						(ExpressionPackage.Literals.PREDICATE_BOOLEAN_VARIABLE__FEATURE,
						 WafFactory.eINSTANCE.createFeaturePathAssociation()));

				newChildDescriptors.add
					(createChildParameter
						(ExpressionPackage.Literals.PREDICATE_BOOLEAN_VARIABLE__FEATURE,
						 WafFactory.eINSTANCE.createFeaturePathLabel()));

				return null;
			}
 
			/**
			 * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
			 * @generated
			 */
			@Override
			public Object casePredicateEqualityOperator(PredicateEqualityOperator object) {
				newChildDescriptors.add
					(createChildParameter
						(ExpressionPackage.Literals.PREDICATE_EQUALITY_OPERATOR__LEFT,
						 WafFactory.eINSTANCE.createFeaturePathAttribute()));

				newChildDescriptors.add
					(createChildParameter
						(ExpressionPackage.Literals.PREDICATE_EQUALITY_OPERATOR__LEFT,
						 WafFactory.eINSTANCE.createFeaturePathAssociation()));

				newChildDescriptors.add
					(createChildParameter
						(ExpressionPackage.Literals.PREDICATE_EQUALITY_OPERATOR__LEFT,
						 WafFactory.eINSTANCE.createFeaturePathLabel()));

				newChildDescriptors.add
					(createChildParameter
						(ExpressionPackage.Literals.PREDICATE_EQUALITY_OPERATOR__RIGHT,
						 WafFactory.eINSTANCE.createFeaturePathAttribute()));

				newChildDescriptors.add
					(createChildParameter
						(ExpressionPackage.Literals.PREDICATE_EQUALITY_OPERATOR__RIGHT,
						 WafFactory.eINSTANCE.createFeaturePathAssociation()));

				newChildDescriptors.add
					(createChildParameter
						(ExpressionPackage.Literals.PREDICATE_EQUALITY_OPERATOR__RIGHT,
						 WafFactory.eINSTANCE.createFeaturePathLabel()));

				return null;
			}
 
			/**
			 * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
			 * @generated
			 */
			@Override
			public Object casePredicateComparisonOperator(PredicateComparisonOperator object) {
				newChildDescriptors.add
					(createChildParameter
						(ExpressionPackage.Literals.PREDICATE_COMPARISON_OPERATOR__LEFT,
						 WafFactory.eINSTANCE.createFeaturePathAttribute()));

				newChildDescriptors.add
					(createChildParameter
						(ExpressionPackage.Literals.PREDICATE_COMPARISON_OPERATOR__LEFT,
						 WafFactory.eINSTANCE.createFeaturePathAssociation()));

				newChildDescriptors.add
					(createChildParameter
						(ExpressionPackage.Literals.PREDICATE_COMPARISON_OPERATOR__LEFT,
						 WafFactory.eINSTANCE.createFeaturePathLabel()));

				newChildDescriptors.add
					(createChildParameter
						(ExpressionPackage.Literals.PREDICATE_COMPARISON_OPERATOR__RIGHT,
						 WafFactory.eINSTANCE.createFeaturePathAttribute()));

				newChildDescriptors.add
					(createChildParameter
						(ExpressionPackage.Literals.PREDICATE_COMPARISON_OPERATOR__RIGHT,
						 WafFactory.eINSTANCE.createFeaturePathAssociation()));

				newChildDescriptors.add
					(createChildParameter
						(ExpressionPackage.Literals.PREDICATE_COMPARISON_OPERATOR__RIGHT,
						 WafFactory.eINSTANCE.createFeaturePathLabel()));

				return null;
			}
 
			/**
			 * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
			 * @generated
			 */
			@Override
			public Object casePredicateInOperator(PredicateInOperator object) {
				newChildDescriptors.add
					(createChildParameter
						(ExpressionPackage.Literals.PREDICATE_IN_OPERATOR__LEFT,
						 WafFactory.eINSTANCE.createFeaturePathAttribute()));

				newChildDescriptors.add
					(createChildParameter
						(ExpressionPackage.Literals.PREDICATE_IN_OPERATOR__LEFT,
						 WafFactory.eINSTANCE.createFeaturePathAssociation()));

				newChildDescriptors.add
					(createChildParameter
						(ExpressionPackage.Literals.PREDICATE_IN_OPERATOR__LEFT,
						 WafFactory.eINSTANCE.createFeaturePathLabel()));

				newChildDescriptors.add
					(createChildParameter
						(ExpressionPackage.Literals.PREDICATE_IN_OPERATOR__RIGHT,
						 WafFactory.eINSTANCE.createFeaturePathAttribute()));

				newChildDescriptors.add
					(createChildParameter
						(ExpressionPackage.Literals.PREDICATE_IN_OPERATOR__RIGHT,
						 WafFactory.eINSTANCE.createFeaturePathAssociation()));

				newChildDescriptors.add
					(createChildParameter
						(ExpressionPackage.Literals.PREDICATE_IN_OPERATOR__RIGHT,
						 WafFactory.eINSTANCE.createFeaturePathLabel()));

				return null;
			}
 
			/**
			 * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
			 * @generated
			 */
			@Override
			public Object casePredicateIsOperator(PredicateIsOperator object) {
				newChildDescriptors.add
					(createChildParameter
						(ExpressionPackage.Literals.PREDICATE_IS_OPERATOR__LEFT,
						 WafFactory.eINSTANCE.createFeaturePathAttribute()));

				newChildDescriptors.add
					(createChildParameter
						(ExpressionPackage.Literals.PREDICATE_IS_OPERATOR__LEFT,
						 WafFactory.eINSTANCE.createFeaturePathAssociation()));

				newChildDescriptors.add
					(createChildParameter
						(ExpressionPackage.Literals.PREDICATE_IS_OPERATOR__LEFT,
						 WafFactory.eINSTANCE.createFeaturePathLabel()));

				newChildDescriptors.add
					(createChildParameter
						(ExpressionPackage.Literals.PREDICATE_IS_OPERATOR__RIGHT,
						 WafFactory.eINSTANCE.createFeaturePathAttribute()));

				newChildDescriptors.add
					(createChildParameter
						(ExpressionPackage.Literals.PREDICATE_IS_OPERATOR__RIGHT,
						 WafFactory.eINSTANCE.createFeaturePathAssociation()));

				newChildDescriptors.add
					(createChildParameter
						(ExpressionPackage.Literals.PREDICATE_IS_OPERATOR__RIGHT,
						 WafFactory.eINSTANCE.createFeaturePathLabel()));

				return null;
			}
 
			/**
			 * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
			 * @generated
			 */
			@Override
			public Object casePredicateLikeOperator(PredicateLikeOperator object) {
				newChildDescriptors.add
					(createChildParameter
						(ExpressionPackage.Literals.PREDICATE_LIKE_OPERATOR__LEFT,
						 WafFactory.eINSTANCE.createFeaturePathAttribute()));

				newChildDescriptors.add
					(createChildParameter
						(ExpressionPackage.Literals.PREDICATE_LIKE_OPERATOR__LEFT,
						 WafFactory.eINSTANCE.createFeaturePathAssociation()));

				newChildDescriptors.add
					(createChildParameter
						(ExpressionPackage.Literals.PREDICATE_LIKE_OPERATOR__LEFT,
						 WafFactory.eINSTANCE.createFeaturePathLabel()));

				newChildDescriptors.add
					(createChildParameter
						(ExpressionPackage.Literals.PREDICATE_LIKE_OPERATOR__RIGHT,
						 WafFactory.eINSTANCE.createFeaturePathAttribute()));

				newChildDescriptors.add
					(createChildParameter
						(ExpressionPackage.Literals.PREDICATE_LIKE_OPERATOR__RIGHT,
						 WafFactory.eINSTANCE.createFeaturePathAssociation()));

				newChildDescriptors.add
					(createChildParameter
						(ExpressionPackage.Literals.PREDICATE_LIKE_OPERATOR__RIGHT,
						 WafFactory.eINSTANCE.createFeaturePathLabel()));

				return null;
			}
 
			/**
			 * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
			 * @generated
			 */
			@Override
			public Object casePredicateIsEmpty(PredicateIsEmpty object) {
				newChildDescriptors.add
					(createChildParameter
						(ExpressionPackage.Literals.PREDICATE_IS_EMPTY__FEATURE,
						 WafFactory.eINSTANCE.createFeaturePathAttribute()));

				newChildDescriptors.add
					(createChildParameter
						(ExpressionPackage.Literals.PREDICATE_IS_EMPTY__FEATURE,
						 WafFactory.eINSTANCE.createFeaturePathAssociation()));

				newChildDescriptors.add
					(createChildParameter
						(ExpressionPackage.Literals.PREDICATE_IS_EMPTY__FEATURE,
						 WafFactory.eINSTANCE.createFeaturePathLabel()));

				return null;
			}
 
			/**
			 * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
			 * @generated
			 */
			@Override
			public Object casePredicateIsNull(PredicateIsNull object) {
				newChildDescriptors.add
					(createChildParameter
						(ExpressionPackage.Literals.PREDICATE_IS_NULL__FEATURE,
						 WafFactory.eINSTANCE.createFeaturePathAttribute()));

				newChildDescriptors.add
					(createChildParameter
						(ExpressionPackage.Literals.PREDICATE_IS_NULL__FEATURE,
						 WafFactory.eINSTANCE.createFeaturePathAssociation()));

				newChildDescriptors.add
					(createChildParameter
						(ExpressionPackage.Literals.PREDICATE_IS_NULL__FEATURE,
						 WafFactory.eINSTANCE.createFeaturePathLabel()));

				return null;
			}
 
			/**
			 * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
			 * @generated
			 */
			protected CommandParameter createChildParameter(Object feature, Object child) {
				return new CommandParameter(null, feature, child);
			}

		}

		/**
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		public Collection<Object> getNewChildDescriptors(Object object, EditingDomain editingDomain) {
			ArrayList<Object> result = new ArrayList<Object>();
			new CreationSwitch(result, editingDomain).doSwitch((EObject)object);
			return result;
		}

		/**
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		public ResourceLocator getResourceLocator() {
			return WafEditPlugin.INSTANCE;
		}
	}

}
